### PR TITLE
Add nvmrc file

### PR DESCRIPTION
**Pull request by timabell**
Same as for frontend.
Didn't seem to help, but putting it out there for discussion

### CODE REVIEW

**Comment by heidar** [comment]
> https://docs.npmjs.com/files/package.json#engines
> 
> nvmrc is a third party tooling
> 
> tackle the problem at the source please

Do these solve the same problems?

**Comment by timabell** [comment]
The reason I had failures was because I had the nodejs package install because of jekyll

```
$ apt show nodejs
Package: nodejs
Version: 4.2.6~dfsg-1ubuntu4.2
```

ref https://github.com/ai/autoprefixer-rails/issues/144#issuecomment-418288034

**Comment by defong** [comment]
> > https://docs.npmjs.com/files/package.json#engines
> > nvmrc is a third party tooling
> > tackle the problem at the source please
> 
> Do these solve the same problems?

yes but no, if you use nvm or know of it, then yes, if you don't you then the source of the problem is not solved (yarn/node), `nvmrc` ask you to use that version vs `package.json` tells you to use that version

plus nvm is not cross platform as far as I remember

image

**Comment by heidar** [comment]
> > > https://docs.npmjs.com/files/package.json#engines
> > > nvmrc is a third party tooling
> > > tackle the problem at the source please
> > 
> > 
> > Do these solve the same problems?
> 
> yes but no, if you use nvm or know of it, then yes, if you don't you then the source of the problem is not solved (yarn/node), `nvmrc` ask you to use that version vs `package.json` tells you to use that version
> 
> plus nvm is not cross platform as far as I remember
> 
> image

Makes sense.

Apparently node/npm doesn't give a crap but yarn does look at engines. So this isn't really needed, but I don't see the harm in having it.

**Pull request merged**
