### PR TITLE
1170-bump-webpack

### PR DESCRIPTION
**Pull request by dankmitchell**
### Context
Webpack

### Changes proposed in this pull request
Bump Webpack to v4.0

### CODE REVIEW

**Comment by dankmitchell** [comment]
[Bump webpack and remove security vulnerability alert on Github](https://trello.com/c/DREXkwoA/1170-bump-webpack-and-remove-security-vulnerability-alert-on-github)

**Comment by dankmitchell** [comment]
@tvararu this project is using the asset pipeline for images and CSS so that functionality isn’t required.

We should make this project consistent by moving images and CSS into webpack but it’s out of scope for this PR.

**Comment by tvararu** [comment]
@dankmitchell ok! :)

**Comment by tvararu** [comment]
Approved as this is the support project and even if this doesn't work fully the potential impact is low :shipit:

**Pull request merged**
