### PR TITLE
Apply linter suggestions

### PR DESCRIPTION
**Pull request by timabell**
This is the result of running:

`bundle exec rubocop app config db lib spec Gemfile --format clang -a`

### CODE REVIEW

**Comment by benilovj** [comment]
> All looks reasonable to me. How's our test coverage on this app? ;)

Not too bad actually!

**Comment by timabell** [comment]
rebased & updated CI commands to match

**Comment by heidar** [comment]
I was going to pick this up but noticed that the linter wasn't configured as on our other apps.

I've opened a PR to address that: https://github.com/DFE-Digital/manage-courses-support/pull/143

I think this is using the default rubocop rules, that we don't use. Can we close this?

**Comment by heidar** [comment]
Closing in favour of #143

**Pull request closed without merging**
